config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  get 'password_resets/new'
  # root route
  root 'sessions#index'
  # login route
  get 'login', to: "sessions#index"
  post 'login', to: "sessions#create"
  get 'register', to: "sessions#new"
  post 'register', to: "sessions#register"
  get 'authorized', to: 'sessions#page_requires_login'
  get 'logout', to: 'sessions#destory'

  # user routes
  get '/users/export', to: 'users#export'
  resources :users
  # post routes
  get '/posts/export', to: 'posts#export'
  resources :posts
  # resert password
  resources :password_resets
  get '/password_resets/.*/edit/', to: 'password_resets#edit'
  # not found route
  get ':not_found' => 'posts#index',
  :constraints => { :not_found => /.*/ }
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates_presence_of :title, message: "can't be blank"
  validates :description, presence: true, length: { minimum: 10 }

  paginates_per 5

  def self.search(query, user_id)
    if User.is_admin(user_id)
        where(["title OR description LIKE ?", "%#{query}%"])
    else
        where(["title OR description LIKE ?", "%#{query}%"]).where(:create_user_id => user_id)
    end
  end
end

app/controllers/posts_controller.rb
require "csv"

class PostsController < ApplicationController
  # index post list
  def index
    user_id = session[:user_id]
    if params[:search]
      @posts = PostsService.search_post(params[:search], params[:page], user_id)
    else
      @posts = PostsService.get_posts(params[:page], user_id)
    end
  end

  # Post Detail
  def show
    @post = PostsService.get_post(params[:id])
  end

  # New Post form
  def new
    @post = Post.new
  end

  # Edit Post form
  def edit
    @post = PostsService.edit_post(params[:id])
  end

  # Create a new Post
  def create
    user_id = session[:user_id]
    @post = PostsService.create_post(post_params, user_id)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # Update post
  def update
    @post = PostsService.update_post(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :updated, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end  
  end

  # Delete post
  def destroy
    PostsService.delete_post(params[:id])

    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully deleted.' }
      format.json { render :show, status: :deleted }
    end  
  end

  # csv export
  def export
    user_id = session[:user_id]
    @posts = PostsService.export_csv(user_id)
    
    respond_to do |format|
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=posts.csv"
      end
    end
  end

  # post parameters 
  def post_params
    params.require(:post).permit(:title, :description, :status, :create_user_id, :updated_user_id, :updated_at)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="form-group row">
    <div class="col-md-2"> <%= form.label :title %> </div>
      <div class="col-md-8"><%= form.text_field :title, class: "form-control" %></div>
    </div>
  <br/>
  <div class="form-group row">
    <div class="col-md-2"> <%= form.label :description %> </div>
      <div class="col-md-8"> <%= form.text_area :description, class: "form-control" %> </div>
  </div>
  <br/>
  <div class="form-group row mb-0">
  <div class="col-md-8 offset-md-2 text-center">
    <%= link_to "Back", users_path ,class: "btn btn-success" %>
    <%= form.submit :class => "btn btn-success" %>
    <%= button_tag "Clear", type: :reset, class: "btn btn-success reset" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger w-50 mx-auto" role="alert">
    <ul>
      <% @post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="card w-50 mx-auto">
  <div class="card-header">
    Edit Post
  </div>
  <div class="card-body">
    <%= render "form", post: @post %>
  </div>
</div>

app/views/posts/export.csv.erb
<%- headers = [
              'Title',
              'Description',
              'Status',
              'Create User ID', 
              'Update User ID',
              'Created Date', 
              'Updated Date'
              ] -%>
<%= CSV.generate_line headers, :row_sep => ?\t, :quote_char => ?\ %>
<%- @posts.each do |post| -%>
  <%= CSV.generate_line([
      post.title, 
      post.description, 
      post.status, 
      post.create_user_id, 
      post.updated_user_id,
      post.created_at.strftime('%Y/%m/%d'), 
      post.updated_at.strftime('%Y/%m/%d')
    ]).html_safe -%>
<%- end -%>

app/views/posts/index.html.erb
<% if notice %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="text-right">
  <%= link_to "New Post", new_post_path, class: "btn btn-success" %>
  <a href="/posts/export.csv" class="btn btn-success">CSV Export</a>
</div>
<div class="py-4">
<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col-2 text-left">Post List</div>
      <div class="col-6"></div>
      <div class="col-4 text-right">
        <%= form_tag posts_path, :method => :get, class: "d-flex" do %>
          <%= text_field_tag :search, params[:search], class: 'form-control rounded', placeholder: "Search with title" %>
          <%= submit_tag "Search", class: "btn btn-outline-success ml-2" do %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-body"> 
    <table class="table table-responsive table-bordered">
        <thead>
            <tr>
                <th>Post title</th>
                <th>Post Description</th>
                <th>Posted User</th>
                <th>Posted Date</th>
                <th collapse=2>Operation</th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |post| %>
            <tr>
                <td><%= link_to post.title, post %></td>
                <td><%= post.description %></td>
                <td><%= post.create_user_id %></td>
                <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
                <td class="text-center"><%= link_to "Edit", edit_post_path(post) ,class: "btn btn-success" %>
                <%= link_to "Destroy", post_path(post),
                                method: :delete,
                                data: { confirm: "Are you sure?" },
                                class: "btn btn-danger" 
                                %></td>
            </tr>
            <%end%>
        </tbody>
    </table>
    <%= paginate @posts %>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger w-50 mx-auto" role="alert">
    <ul>
      <% @post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="card w-50 mx-auto">
  <div class="card-header">
    Create Post
  </div>
  <div class="card-body">
    <%= render "form", post: @post %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card">
  <div class="card-header">
    Post Details
  </div>
  <div class="card-body"><div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Title</label>
    <div class="col-sm-10">
        <label for="staticEmail" class="col-sm-10 col-form-label"><%= @post.title %></label>
    </div>
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
        <label for="staticEmail" class="col-sm-10 col-form-label"><%= @post.description %></label>
    </div>
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Status</label>
    <div class="col-sm-10">
        <label for="staticEmail" class="col-sm-10 col-form-label"><%= @post.status == 1 ? 'Active' : 'Unactive' %></label>
    </div>
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Created Date</label>
    <div class="col-sm-10">
        <label for="staticEmail" class="col-sm-10 col-form-label"><%= @post.created_at.strftime('%Y/%m/%d') %></label>
    </div>
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Created User</label>
    <div class="col-sm-10">
        <label for="staticEmail" class="col-sm-10 col-form-label"><%= @post.create_user_id == 1 ? 'Admin' : 'User' %></label>
    </div>
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Updated Date</label>
    <div class="col-sm-10">
        <label for="staticEmail" class="col-sm-10 col-form-label"><%= @post.updated_at.strftime('%Y/%m/%d') %></label>
    </div>
</div>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Updated User</label>
    <div class="col-sm-10">
        <label for="staticEmail" class="col-sm-10 col-form-label"><%= @post.updated_user_id == 1 ? 'Admin' : 'User' %></label>
    </div>
</div>
  </div>
</div>
<%= link_to "Back", posts_path ,class: "btn btn-success mt-3" %>